# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af484d71ee8caa6dfe1357afbe59152421633f5bd0a4c1d7585f908ca89b9c975b283ef5ab900e9ca1ee4372f544c1b6f9436b1318c060af3786bc3aff5ed038

test:
  secret_key_base: 9f23a76d478a7c5b25a275e15e7a60217008f65f635b2d7e676a7170e238c0f96716bccc7a1a4c78291174282e0a08eb431ba8403a136768c9a257ee7d4cbd34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
